volumes:
  plants:
    external: true
  pg-admin:
    external: true
services:
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      SIGNING_KEY: 1a837fcf4dd58680ea31173d4a990375ffe652fdac1a851bd94328823fdaf30b
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_ACCOUNTS_HOST: http://localhost:8000
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      - db
    environment:
      SIGNING_KEY: 16ec5d253329d08ecbc0fdf20eff623d9741b4d8aac21b3029a1d5dd4f4b7b9b
      WAIT_HOSTS: db:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      DATABASE_URL: postgresql://plants_user:plants_pwd@db/plants_db
      HOUSEPLANTS_API_KEY: ${HOUSEPLANTS_API_KEY}
  db:
    build:
      context: ./data
      dockerfile: Dockerfile.dev
    volumes:
      - plants:/var/lib/postgresql/data
    environment:
      SIGNING_KEY: 35266a7c7c61c083701cee654f1afba2df4b5edf128b0607f4b3468eddda8fac
      POSTGRES_PASSWORD: plants_pwd
      POSTGRES_USER: plants_user
      POSTGRES_DB: plants_db
    ports:
      - "15432:5432"
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      SIGNING_KEY: b6bc596dd1b47e992e2e19097df0f4f27289fa9b2332765434e3898a8071b835
      PGADMIN_DEFAULT_EMAIL: mattsun220@gmail.com
      PGADMIN_DEFAULT_PASSWORD: plants
      PGADMIN_DISABLE_POSTFIX: 1
