volumes:
  plants:
    external: true
services:
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
        - ./ghi:/app
    ports:
        - "3000:3000"
    environment:
        HOST_OS: ${OS}
        NODE_ENV: development
        HOST: "0.0.0.0"
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      DATABASE_URL: postgresql://plants_user:plants_pwd@db/plants_db
      # WAIT_HOSTS: postgres:5432
  db:
    build:
      context: data
      dockerfile: Dockerfile.dev
    volumes:
      - plants:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: plants_pwd
      POSTGRES_USER: plants_user
      POSTGRES_DB: plants_db
    ports:
      - "15432:5432"
