volumes:
  plants:
    external: true
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      DATABASE_URL: postgresql://plants_user:plants_pwd@db/plants_db
      # WAIT_HOSTS: postgres:5432
  db:
    build:
      context: api
      dockerfile: Dockerfile.dev
    volumes:
      - plants:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: plants_pwd
      POSTGRES_USER: plants_user
      POSTGRES_DB: plants_db
    ports:
      - "15432:5432"
